AzerothAutofarmData = {
    categories = {
        { key = "favorites", name = "Favorites" },
        { key = "all", name = "All Materials" },
        { key = "mining", name = "Mining" },
        { key = "herbalism", name = "Herbalism" },
        { key = "leather", name = "Leather & Scales" },
        { key = "cloth", name = "Cloth & Silk" },
        { key = "meat", name = "Cooking Meat" },
        { key = "elemental", name = "Elementals" },
        { key = "fishing", name = "Fishing Schools" },
        { key = "gems", name = "Gems" },
    },

    materials = {
        -- Mining: ore and stone found in mineral nodes.
        { id = 2770, name = "Copper Ore", category = "mining", tier = "Classic" },
        { id = 2835, name = "Rough Stone", category = "mining", tier = "Classic" },
        { id = 2771, name = "Tin Ore", category = "mining", tier = "Classic" },
        { id = 2836, name = "Coarse Stone", category = "mining", tier = "Classic" },
        { id = 2775, name = "Silver Ore", category = "mining", tier = "Classic" },
        { id = 2772, name = "Iron Ore", category = "mining", tier = "Classic" },
        { id = 2838, name = "Heavy Stone", category = "mining", tier = "Classic" },
        { id = 2776, name = "Gold Ore", category = "mining", tier = "Classic" },
        { id = 3858, name = "Mithril Ore", category = "mining", tier = "Classic" },
        { id = 7912, name = "Solid Stone", category = "mining", tier = "Classic" },
        { id = 7911, name = "Truesilver Ore", category = "mining", tier = "Classic" },
        { id = 10620, name = "Thorium Ore", category = "mining", tier = "Classic" },
        { id = 12365, name = "Dense Stone", category = "mining", tier = "Classic" },
        { id = 23424, name = "Fel Iron Ore", category = "mining", tier = "Outland" },
        { id = 23425, name = "Adamantite Ore", category = "mining", tier = "Outland" },
        { id = 23426, name = "Khorium Ore", category = "mining", tier = "Outland" },
        { id = 23427, name = "Eternium Ore", category = "mining", tier = "Outland" },
        { id = 36909, name = "Cobalt Ore", category = "mining", tier = "Northrend" },
        { id = 36912, name = "Saronite Ore", category = "mining", tier = "Northrend" },
        { id = 36910, name = "Titanium Ore", category = "mining", tier = "Northrend" },

        -- Herbalism.
        { id = 2447, name = "Peacebloom", category = "herbalism", tier = "Classic" },
        { id = 765, name = "Silverleaf", category = "herbalism", tier = "Classic" },
        { id = 2449, name = "Earthroot", category = "herbalism", tier = "Classic" },
        { id = 785, name = "Mageroyal", category = "herbalism", tier = "Classic" },
        { id = 2450, name = "Briarthorn", category = "herbalism", tier = "Classic" },
        { id = 3820, name = "Stranglekelp", category = "herbalism", tier = "Classic" },
        { id = 2453, name = "Bruiseweed", category = "herbalism", tier = "Classic" },
        { id = 3355, name = "Wild Steelbloom", category = "herbalism", tier = "Classic" },
        { id = 3369, name = "Grave Moss", category = "herbalism", tier = "Classic" },
        { id = 3356, name = "Kingsblood", category = "herbalism", tier = "Classic" },
        { id = 3357, name = "Liferoot", category = "herbalism", tier = "Classic" },
        { id = 3818, name = "Fadeleaf", category = "herbalism", tier = "Classic" },
        { id = 3821, name = "Goldthorn", category = "herbalism", tier = "Classic" },
        { id = 3358, name = "Khadgar's Whisker", category = "herbalism", tier = "Classic" },
        { id = 3819, name = "Wintersbite", category = "herbalism", tier = "Classic" },
        { id = 4625, name = "Firebloom", category = "herbalism", tier = "Classic" },
        { id = 8831, name = "Purple Lotus", category = "herbalism", tier = "Classic" },
        { id = 8836, name = "Arthas' Tears", category = "herbalism", tier = "Classic" },
        { id = 8838, name = "Sungrass", category = "herbalism", tier = "Classic" },
        { id = 8839, name = "Blindweed", category = "herbalism", tier = "Classic" },
        { id = 8845, name = "Ghost Mushroom", category = "herbalism", tier = "Classic" },
        { id = 8846, name = "Gromsblood", category = "herbalism", tier = "Classic" },
        { id = 13464, name = "Golden Sansam", category = "herbalism", tier = "Classic" },
        { id = 13463, name = "Dreamfoil", category = "herbalism", tier = "Classic" },
        { id = 13465, name = "Mountain Silversage", category = "herbalism", tier = "Classic" },
        { id = 13466, name = "Plaguebloom", category = "herbalism", tier = "Classic" },
        { id = 13467, name = "Icecap", category = "herbalism", tier = "Classic" },
        { id = 13468, name = "Black Lotus", category = "herbalism", tier = "Classic" },
        { id = 22785, name = "Felweed", category = "herbalism", tier = "Outland" },
        { id = 22786, name = "Dreaming Glory", category = "herbalism", tier = "Outland" },
        { id = 22787, name = "Ragveil", category = "herbalism", tier = "Outland" },
        { id = 22788, name = "Flame Cap", category = "herbalism", tier = "Outland" },
        { id = 22789, name = "Terocone", category = "herbalism", tier = "Outland" },
        { id = 22790, name = "Ancient Lichen", category = "herbalism", tier = "Outland" },
        { id = 22791, name = "Netherbloom", category = "herbalism", tier = "Outland" },
        { id = 22792, name = "Nightmare Vine", category = "herbalism", tier = "Outland" },
        { id = 22793, name = "Mana Thistle", category = "herbalism", tier = "Outland" },
        { id = 36901, name = "Goldclover", category = "herbalism", tier = "Northrend" },
        { id = 36904, name = "Tiger Lily", category = "herbalism", tier = "Northrend" },
        { id = 36907, name = "Talandra's Rose", category = "herbalism", tier = "Northrend" },
        { id = 36903, name = "Adder's Tongue", category = "herbalism", tier = "Northrend" },
        { id = 36905, name = "Lichbloom", category = "herbalism", tier = "Northrend" },
        { id = 36906, name = "Icethorn", category = "herbalism", tier = "Northrend" },
        { id = 36908, name = "Frost Lotus", category = "herbalism", tier = "Northrend" },

        -- Skinning materials.
        { id = 2934, name = "Ruined Leather Scraps", category = "leather", tier = "Classic" },
        { id = 2318, name = "Light Leather", category = "leather", tier = "Classic" },
        { id = 783, name = "Light Hide", category = "leather", tier = "Classic" },
        { id = 2319, name = "Medium Leather", category = "leather", tier = "Classic" },
        { id = 4232, name = "Medium Hide", category = "leather", tier = "Classic" },
        { id = 4234, name = "Heavy Leather", category = "leather", tier = "Classic" },
        { id = 4235, name = "Heavy Hide", category = "leather", tier = "Classic" },
        { id = 4304, name = "Thick Leather", category = "leather", tier = "Classic" },
        { id = 8169, name = "Thick Hide", category = "leather", tier = "Classic" },
        { id = 8170, name = "Rugged Leather", category = "leather", tier = "Classic" },
        { id = 8171, name = "Rugged Hide", category = "leather", tier = "Classic" },
        { id = 8154, name = "Scorpid Scale", category = "leather", tier = "Classic" },
        { id = 8165, name = "Worn Dragonscale", category = "leather", tier = "Classic" },
        { id = 8167, name = "Turtle Scale", category = "leather", tier = "Classic" },
        { id = 15412, name = "Green Dragonscale", category = "leather", tier = "Classic" },
        { id = 15414, name = "Red Dragonscale", category = "leather", tier = "Classic" },
        { id = 15415, name = "Blue Dragonscale", category = "leather", tier = "Classic" },
        { id = 15416, name = "Black Dragonscale", category = "leather", tier = "Classic" },
        { id = 15417, name = "Devilsaur Leather", category = "leather", tier = "Classic" },
        { id = 25649, name = "Knothide Leather Scraps", category = "leather", tier = "Outland" },
        { id = 21887, name = "Knothide Leather", category = "leather", tier = "Outland" },
        { id = 25699, name = "Crystal Infused Leather", category = "leather", tier = "Outland" },
        { id = 25700, name = "Fel Scales", category = "leather", tier = "Outland" },
        { id = 25707, name = "Fel Hide", category = "leather", tier = "Outland" },
        { id = 25708, name = "Thick Clefthoof Leather", category = "leather", tier = "Outland" },
        { id = 29539, name = "Cobra Scales", category = "leather", tier = "Outland" },
        { id = 29547, name = "Wind Scales", category = "leather", tier = "Outland" },
        { id = 29548, name = "Nether Dragonscales", category = "leather", tier = "Outland" },
        { id = 33567, name = "Borean Leather Scraps", category = "leather", tier = "Northrend" },
        { id = 33568, name = "Borean Leather", category = "leather", tier = "Northrend" },
        { id = 38557, name = "Icy Dragonscale", category = "leather", tier = "Northrend" },
        { id = 38558, name = "Nerubian Chitin", category = "leather", tier = "Northrend" },
        { id = 38561, name = "Jormungar Scale", category = "leather", tier = "Northrend" },
        { id = 44128, name = "Arctic Fur", category = "leather", tier = "Northrend" },

        -- Cloth and creature-dropped tailoring materials.
        { id = 2589, name = "Linen Cloth", category = "cloth", tier = "Classic" },
        { id = 2592, name = "Wool Cloth", category = "cloth", tier = "Classic" },
        { id = 4306, name = "Silk Cloth", category = "cloth", tier = "Classic" },
        { id = 4338, name = "Mageweave Cloth", category = "cloth", tier = "Classic" },
        { id = 14047, name = "Runecloth", category = "cloth", tier = "Classic" },
        { id = 14256, name = "Felcloth", category = "cloth", tier = "Classic" },
        { id = 3182, name = "Spider's Silk", category = "cloth", tier = "Classic" },
        { id = 4337, name = "Thick Spider's Silk", category = "cloth", tier = "Classic" },
        { id = 10285, name = "Shadow Silk", category = "cloth", tier = "Classic" },
        { id = 14227, name = "Ironweb Spider Silk", category = "cloth", tier = "Classic" },
        { id = 21877, name = "Netherweave Cloth", category = "cloth", tier = "Outland" },
        { id = 21881, name = "Netherweb Spider Silk", category = "cloth", tier = "Outland" },
        { id = 33470, name = "Frostweave Cloth", category = "cloth", tier = "Northrend" },

        -- Common cooking meat from outdoor creatures.
        { id = 769, name = "Chunk of Boar Meat", category = "meat", tier = "Classic" },
        { id = 2672, name = "Stringy Wolf Meat", category = "meat", tier = "Classic" },
        { id = 2674, name = "Crawler Meat", category = "meat", tier = "Classic" },
        { id = 3173, name = "Bear Meat", category = "meat", tier = "Classic" },
        { id = 12037, name = "Mystery Meat", category = "meat", tier = "Classic" },
        { id = 12184, name = "Raptor Flesh", category = "meat", tier = "Classic" },
        { id = 12202, name = "Tiger Meat", category = "meat", tier = "Classic" },
        { id = 12205, name = "White Spider Meat", category = "meat", tier = "Classic" },
        { id = 12208, name = "Tender Wolf Meat", category = "meat", tier = "Classic" },
        { id = 27671, name = "Buzzard Meat", category = "meat", tier = "Outland" },
        { id = 27674, name = "Ravager Flesh", category = "meat", tier = "Outland" },
        { id = 27678, name = "Clefthoof Meat", category = "meat", tier = "Outland" },
        { id = 27681, name = "Warped Flesh", category = "meat", tier = "Outland" },
        { id = 27682, name = "Talbuk Venison", category = "meat", tier = "Outland" },
        { id = 35562, name = "Bear Flank", category = "meat", tier = "Northrend" },
        { id = 43009, name = "Shoveltusk Flank", category = "meat", tier = "Northrend" },
        { id = 43010, name = "Worm Meat", category = "meat", tier = "Northrend" },
        { id = 43011, name = "Worg Haunch", category = "meat", tier = "Northrend" },
        { id = 43012, name = "Rhino Meat", category = "meat", tier = "Northrend" },
        { id = 43013, name = "Chilled Meat", category = "meat", tier = "Northrend" },

        -- Elemental drops. Combined Primals and Eternals are crafted, so their components are listed instead.
        { id = 7067, name = "Elemental Earth", category = "elemental", tier = "Classic" },
        { id = 7068, name = "Elemental Fire", category = "elemental", tier = "Classic" },
        { id = 7069, name = "Elemental Air", category = "elemental", tier = "Classic" },
        { id = 7070, name = "Elemental Water", category = "elemental", tier = "Classic" },
        { id = 7075, name = "Core of Earth", category = "elemental", tier = "Classic" },
        { id = 7076, name = "Essence of Earth", category = "elemental", tier = "Classic" },
        { id = 7077, name = "Heart of Fire", category = "elemental", tier = "Classic" },
        { id = 7078, name = "Essence of Fire", category = "elemental", tier = "Classic" },
        { id = 7079, name = "Globe of Water", category = "elemental", tier = "Classic" },
        { id = 7080, name = "Essence of Water", category = "elemental", tier = "Classic" },
        { id = 7081, name = "Breath of Wind", category = "elemental", tier = "Classic" },
        { id = 7082, name = "Essence of Air", category = "elemental", tier = "Classic" },
        { id = 22572, name = "Mote of Air", category = "elemental", tier = "Outland" },
        { id = 22573, name = "Mote of Earth", category = "elemental", tier = "Outland" },
        { id = 22574, name = "Mote of Fire", category = "elemental", tier = "Outland" },
        { id = 22575, name = "Mote of Life", category = "elemental", tier = "Outland" },
        { id = 22576, name = "Mote of Mana", category = "elemental", tier = "Outland" },
        { id = 22577, name = "Mote of Shadow", category = "elemental", tier = "Outland" },
        { id = 22578, name = "Mote of Water", category = "elemental", tier = "Outland" },
        { id = 37700, name = "Crystallized Air", category = "elemental", tier = "Northrend" },
        { id = 37701, name = "Crystallized Earth", category = "elemental", tier = "Northrend" },
        { id = 37702, name = "Crystallized Fire", category = "elemental", tier = "Northrend" },
        { id = 37703, name = "Crystallized Shadow", category = "elemental", tier = "Northrend" },
        { id = 37704, name = "Crystallized Life", category = "elemental", tier = "Northrend" },
        { id = 37705, name = "Crystallized Water", category = "elemental", tier = "Northrend" },

        -- Fish which can be found in outdoor fishing-school gameobjects.
        { id = 6291, name = "Raw Brilliant Smallfish", category = "fishing", tier = "Classic" },
        { id = 6289, name = "Raw Longjaw Mud Snapper", category = "fishing", tier = "Classic" },
        { id = 6303, name = "Raw Slitherskin Mackerel", category = "fishing", tier = "Classic" },
        { id = 6308, name = "Raw Bristle Whisker Catfish", category = "fishing", tier = "Classic" },
        { id = 6361, name = "Raw Rainbow Fin Albacore", category = "fishing", tier = "Classic" },
        { id = 6362, name = "Raw Rockscale Cod", category = "fishing", tier = "Classic" },
        { id = 8365, name = "Raw Mithril Head Trout", category = "fishing", tier = "Classic" },
        { id = 13754, name = "Raw Glossy Mightfish", category = "fishing", tier = "Classic" },
        { id = 13756, name = "Raw Summer Bass", category = "fishing", tier = "Classic" },
        { id = 13758, name = "Raw Redgill", category = "fishing", tier = "Classic" },
        { id = 13759, name = "Raw Nightfin Snapper", category = "fishing", tier = "Classic" },
        { id = 13760, name = "Raw Sunscale Salmon", category = "fishing", tier = "Classic" },
        { id = 13888, name = "Darkclaw Lobster", category = "fishing", tier = "Classic" },
        { id = 13889, name = "Raw Whitescale Salmon", category = "fishing", tier = "Classic" },
        { id = 13422, name = "Stonescale Eel", category = "fishing", tier = "Classic" },
        { id = 27422, name = "Barbed Gill Trout", category = "fishing", tier = "Outland" },
        { id = 27425, name = "Spotted Feltail", category = "fishing", tier = "Outland" },
        { id = 27429, name = "Zangarian Sporefish", category = "fishing", tier = "Outland" },
        { id = 27435, name = "Figluster's Mudfish", category = "fishing", tier = "Outland" },
        { id = 27437, name = "Icefin Bluefish", category = "fishing", tier = "Outland" },
        { id = 27438, name = "Golden Darter", category = "fishing", tier = "Outland" },
        { id = 27439, name = "Furious Crawdad", category = "fishing", tier = "Outland" },
        { id = 41800, name = "Deep Sea Monsterbelly", category = "fishing", tier = "Northrend" },
        { id = 41801, name = "Moonglow Cuttlefish", category = "fishing", tier = "Northrend" },
        { id = 41802, name = "Imperial Manta Ray", category = "fishing", tier = "Northrend" },
        { id = 41803, name = "Rockfin Grouper", category = "fishing", tier = "Northrend" },
        { id = 41806, name = "Musselback Sculpin", category = "fishing", tier = "Northrend" },
        { id = 41807, name = "Dragonfin Angelfish", category = "fishing", tier = "Northrend" },
        { id = 41808, name = "Bonescale Snapper", category = "fishing", tier = "Northrend" },
        { id = 41809, name = "Glacial Salmon", category = "fishing", tier = "Northrend" },
        { id = 41813, name = "Nettlefish", category = "fishing", tier = "Northrend" },
        { id = 40199, name = "Pygmy Suckerfish", category = "fishing", tier = "Northrend" },

        -- Uncut gems that can occur in mineral-node loot.
        { id = 774, name = "Malachite", category = "gems", tier = "Classic" },
        { id = 818, name = "Tigerseye", category = "gems", tier = "Classic" },
        { id = 1210, name = "Shadowgem", category = "gems", tier = "Classic" },
        { id = 1206, name = "Moss Agate", category = "gems", tier = "Classic" },
        { id = 1705, name = "Lesser Moonstone", category = "gems", tier = "Classic" },
        { id = 3864, name = "Citrine", category = "gems", tier = "Classic" },
        { id = 7909, name = "Aquamarine", category = "gems", tier = "Classic" },
        { id = 7910, name = "Star Ruby", category = "gems", tier = "Classic" },
        { id = 12361, name = "Blue Sapphire", category = "gems", tier = "Classic" },
        { id = 12363, name = "Arcane Crystal", category = "gems", tier = "Classic" },
        { id = 12364, name = "Huge Emerald", category = "gems", tier = "Classic" },
        { id = 12800, name = "Azerothian Diamond", category = "gems", tier = "Classic" },
        { id = 23077, name = "Blood Garnet", category = "gems", tier = "Outland" },
        { id = 23079, name = "Deep Peridot", category = "gems", tier = "Outland" },
        { id = 21929, name = "Flame Spessarite", category = "gems", tier = "Outland" },
        { id = 23112, name = "Golden Draenite", category = "gems", tier = "Outland" },
        { id = 23117, name = "Azure Moonstone", category = "gems", tier = "Outland" },
        { id = 23107, name = "Shadow Draenite", category = "gems", tier = "Outland" },
        { id = 23436, name = "Living Ruby", category = "gems", tier = "Outland" },
        { id = 23437, name = "Talasite", category = "gems", tier = "Outland" },
        { id = 23438, name = "Star of Elune", category = "gems", tier = "Outland" },
        { id = 23439, name = "Noble Topaz", category = "gems", tier = "Outland" },
        { id = 23440, name = "Dawnstone", category = "gems", tier = "Outland" },
        { id = 23441, name = "Nightseye", category = "gems", tier = "Outland" },
        { id = 36917, name = "Bloodstone", category = "gems", tier = "Northrend" },
        { id = 36920, name = "Sun Crystal", category = "gems", tier = "Northrend" },
        { id = 36923, name = "Chalcedony", category = "gems", tier = "Northrend" },
        { id = 36926, name = "Shadow Crystal", category = "gems", tier = "Northrend" },
        { id = 36929, name = "Huge Citrine", category = "gems", tier = "Northrend" },
        { id = 36932, name = "Dark Jade", category = "gems", tier = "Northrend" },
        { id = 36918, name = "Scarlet Ruby", category = "gems", tier = "Northrend" },
        { id = 36921, name = "Autumn's Glow", category = "gems", tier = "Northrend" },
        { id = 36924, name = "Sky Sapphire", category = "gems", tier = "Northrend" },
        { id = 36927, name = "Twilight Opal", category = "gems", tier = "Northrend" },
        { id = 36930, name = "Monarch Topaz", category = "gems", tier = "Northrend" },
        { id = 36933, name = "Forest Emerald", category = "gems", tier = "Northrend" },
    },
}
